version: '3.8'

services:
  web:
    container_name: adoclic-web
    build:
      context: .
      dockerfile: ./Ado-Clic/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myapp;Username=postgres;Password=postgres
      - MailSettings__SmtpServer=mailcatcher
      - MailSettings__SmtpPort=1025
    depends_on:
      - db
      - mailcatcher

  db:
    container_name: adoclic-db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  mailcatcher:
    container_name: adoclic-mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # Web UI
      - "1025:1025"  # SMTP

volumes:
  pgdata:
